name: Test SvgToVectorCompose

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test CLI help
      run: |
        python main.py --help
    
    - name: Test basic conversion
      run: |
        cd examples
        python basic_conversion.py
    
    - name: Test config-based conversion
      run: |
        cd examples
        python config_based_conversion.py
    
    - name: Verify generated files
      run: |
        # Check if Kotlin files were generated
        find examples/output -name "*.kt" -type f | head -10
        
        # Verify IconPack files exist
        find examples/output -name "*Icons.kt" -type f
    
    - name: Test with custom config
      run: |
        # Create a test config
        cat > test_config.json << EOF
        {
          "input": "examples/input/icons",
          "output": "test_output",
          "package": "com.test.icons",
          "generate_index": true,
          "iconpack_name": "TestIcons",
          "clean": true
        }
        EOF
        
        # Run conversion with custom config
        python main.py --config test_config.json
        
        # Verify output
        ls -la test_output/
        find test_output -name "*.kt" -type f